# Generated by Django 3.2.5 on 2021-07-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210723_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tr_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
